# Generated by Django 6.0.3 on 2026-03-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='app_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rated_stations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
