// =============================================================
// context/NotificationsContext.jsx  — NEW FILE
// =============================================================
// Provides notifications to the whole app.
//
// What it does:
//   - Polls GET /api/notifications/ every 30 seconds
//   - Exposes: notifications[], unreadCount, markRead(), markAllRead()
//   - Re-fetches immediately when called manually (e.g. on bell click)
//
// Notification types generated by the backend (signals.py):
//   order_placed     → "Your order #N has been placed."
//   order_processing → "Your order #N is being prepared."
//   order_shipped    → "Your order #N is out for delivery!"
//   order_delivered  → "Your order #N has been delivered."
//   order_cancelled  → "Your order #N has been cancelled."
// =============================================================

import { createContext, useContext, useState, useEffect, useCallback } from 'react'
import apiClient from '../api/client'

const NotificationsContext = createContext(null)

export function NotificationsProvider({ children }) {
  const [notifications, setNotifications] = useState([])
  const [loading,       setLoading]       = useState(false)

  // ── CRUD: READ — fetch all notifications for the logged-in user ──
  const fetchNotifications = useCallback(async () => {
    setLoading(true)
    try {
      const r = await apiClient.get('/notifications/')
      const data = Array.isArray(r.data) ? r.data : r.data?.results || []
      setNotifications(data)
    } catch {
      // Silently fail — don't break the app if notifications are unavailable
    } finally {
      setLoading(false)
    }
  }, [])

  // Poll every 30 seconds so status changes show up without refreshing
  useEffect(() => {
    fetchNotifications()
    const interval = setInterval(fetchNotifications, 30_000)
    return () => clearInterval(interval)
  }, [fetchNotifications])

  // ── CRUD: UPDATE — mark a single notification as read ───────────
  const markRead = async (id) => {
    try {
      await apiClient.patch(`/notifications/${id}/`, { is_read: true })
      setNotifications(prev =>
        prev.map(n => n.id === id ? { ...n, is_read: true } : n)
      )
    } catch { /* silent */ }
  }

  // ── CRUD: UPDATE — mark all as read (custom action) ─────────────
  const markAllRead = async () => {
    try {
      await apiClient.post('/notifications/mark_all_read/')
      setNotifications(prev => prev.map(n => ({ ...n, is_read: true })))
    } catch { /* silent */ }
  }

  const unreadCount = notifications.filter(n => !n.is_read).length

  return (
    <NotificationsContext.Provider value={{
      notifications,
      unreadCount,
      loading,
      fetchNotifications,
      markRead,
      markAllRead,
    }}>
      {children}
    </NotificationsContext.Provider>
  )
}

export const useNotifications = () => {
  const ctx = useContext(NotificationsContext)
  if (!ctx) throw new Error('useNotifications must be used inside NotificationsProvider')
  return ctx
}