# Generated by Django 6.0.3 on 2026-03-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_hidden_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
