# Generated by Django 6.0.3 on 2026-03-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_price_alter_orderitem_quantity_and_more'),
        ('orders', '0003_order_is_hidden_by_user'),
    ]

    operations = [
    ]
