# =============================================================
# views.py — Orders App
# =============================================================
# CRUD is implemented across three ViewSets, one per table:
#
#   OrderViewSet      → full CRUD for TABLE 1 (Order)
#   OrderItemViewSet  → full CRUD for TABLE 2 (OrderItem)
#   OrderNoteViewSet  → full CRUD for TABLE 3 (OrderNote)
#
# Every method is tagged with the CRUD operation it handles.
# FORM VALIDATION is triggered by serializer.is_valid() in each
# create / update method — errors are returned automatically.
# =============================================================

from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.exceptions import PermissionDenied, NotFound
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from .models import Order, OrderItem, OrderNote
from .serializers import OrderSerializer, OrderItemSerializer, OrderNoteSerializer


# ─────────────────────────────────────────────────────────────
# TABLE 1 — Order ViewSet
# Endpoints (auto-generated by router in urls.py):
#   POST   /api/orders/         → CREATE
#   GET    /api/orders/         → READ (list)
#   GET    /api/orders/{id}/    → READ (detail)
#   PATCH  /api/orders/{id}/    → UPDATE
#   DELETE /api/orders/{id}/    → DELETE
#   POST   /api/orders/{id}/cancel/ → custom cancel action
# ─────────────────────────────────────────────────────────────
class OrderViewSet(viewsets.ModelViewSet):

    serializer_class   = OrderSerializer
    permission_classes = [IsAuthenticated]

    # ── READ — scope queryset to current user (staff sees all) ──
    def get_queryset(self):
        """Return orders for the current user, excluding hidden ones"""
        user = self.request.user
        qs   = Order.objects.all() if user.is_staff else Order.objects.filter(user=user)
        if user.is_staff:
            return Order.objects.filter(is_hidden_by_user=False)
        return Order.objects.filter(user=user, is_hidden_by_user=False)

        # Optional filter: GET /api/orders/?status=pending
        status_filter = self.request.query_params.get('status')
        if status_filter:
            qs = qs.filter(status=status_filter)

        return qs.prefetch_related('items', 'order_notes')

    # ── CRUD: CREATE ────────────────────────────────────────────
    def create(self, request, *args, **kwargs):
        """
        POST /api/orders/
        Body: { shipping_address, notes, status, items: [{product_id, quantity, price}] }
        FORM VALIDATION: serializer.is_valid() runs all validate_*() rules in serializers.py
        """
        # FORM VALIDATION — runs validate_shipping_address, validate_notes, validate_status
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)   # returns 400 with errors if invalid

        # Save order and attach to the logged-in user
        order = serializer.save(user=request.user)

        # CRUD: CREATE — also create any OrderItems sent in the payload
        items_data  = request.data.get('items', [])
        item_errors = []
        for i, item in enumerate(items_data):
            item_ser = OrderItemSerializer(data=item)
            if item_ser.is_valid():
                item_ser.save(order=order)
            else:
                # Collect per-item validation errors without aborting the whole order
                item_errors.append({f"item[{i}]": item_ser.errors})

        # Recompute total_price after all items are saved
        order.compute_total()

        response_data = OrderSerializer(order, context={'request': request}).data
        if item_errors:
            response_data['item_warnings'] = item_errors   # non-fatal item issues

        return Response(response_data, status=status.HTTP_201_CREATED)

    # ── CRUD: UPDATE (partial) ──────────────────────────────────
    def partial_update(self, request, *args, **kwargs):
        """
        PATCH /api/orders/{id}/
        Allowed fields: status, shipping_address, notes
        FORM VALIDATION: validate_status() enforces transition rules
        """
        order = self.get_object()

        # Permission: only owner or staff can update
        if order.user != request.user and not request.user.is_staff:
            raise PermissionDenied("You can only edit your own orders.")

        # FORM VALIDATION — runs validate_status, validate_shipping_address, validate()
        serializer = self.get_serializer(order, data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)

    # ── CRUD: DELETE ────────────────────────────────────────────
    def destroy(self, request, *args, **kwargs):
        """
        DELETE /api/orders/{id}/
        Blocked for shipped or delivered orders.
        """
        order = self.get_object()

        if order.user != request.user and not request.user.is_staff:
            raise PermissionDenied("You can only delete your own orders.")

        # FORM VALIDATION — business rule: cannot delete in-transit orders
        if order.status in ['shipped', 'delivered']:
            return Response(
                {"error": f"Cannot delete an order with status '{order.status}'."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        order.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

    # ── CRUD: UPDATE (custom action — cancel) ───────────────────
    @action(detail=True, methods=['post'], url_path='cancel')
    def cancel(self, request, pk=None):
        """
        POST /api/orders/{id}/cancel/
        Shortcut to cancel a pending or processing order.
        """
        order = self.get_object()

        if order.user != request.user and not request.user.is_staff:
            raise PermissionDenied("You can only cancel your own orders.")

        # FORM VALIDATION — can only cancel before shipping
        if order.status in ['shipped', 'delivered', 'cancelled']:
            return Response(
                {"error": f"Cannot cancel an order with status '{order.status}'."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        order.status = 'cancelled'
        order.save(update_fields=['status'])
        return Response({"message": f"Order #{order.id} cancelled."})


# ─────────────────────────────────────────────────────────────
# TABLE 2 — OrderItem ViewSet
# Endpoints (nested under order via urls.py):
#   POST   /api/orders/{order_pk}/items/        → CREATE
#   GET    /api/orders/{order_pk}/items/        → READ (list)
#   GET    /api/orders/{order_pk}/items/{id}/   → READ (detail)
#   PATCH  /api/orders/{order_pk}/items/{id}/   → UPDATE
#   DELETE /api/orders/{order_pk}/items/{id}/   → DELETE
# ─────────────────────────────────────────────────────────────
class OrderItemViewSet(viewsets.ModelViewSet):

    serializer_class   = OrderItemSerializer
    permission_classes = [IsAuthenticated]

    def _get_order(self):
        """Helper — fetch parent Order and verify the caller owns it."""
        try:
            order = Order.objects.get(pk=self.kwargs['order_pk'])
        except Order.DoesNotExist:
            raise NotFound("Order not found.")
        if order.user != self.request.user and not self.request.user.is_staff:
            raise PermissionDenied("You do not have access to this order.")
        return order

    # ── CRUD: READ ──────────────────────────────────────────────
    def get_queryset(self):
        return OrderItem.objects.filter(order=self._get_order())

    # ── CRUD: CREATE ────────────────────────────────────────────
    def perform_create(self, serializer):
        order = self._get_order()

        # FORM VALIDATION — cannot add items to a closed order
        if order.status in ['delivered', 'cancelled']:
            raise PermissionDenied(
                f"Cannot add items to an order with status '{order.status}'."
            )

        # FORM VALIDATION runs via serializer.is_valid() before perform_create is called
        serializer.save(order=order)
        order.compute_total()   # UPDATE total_price after new item

    # ── CRUD: UPDATE ────────────────────────────────────────────
    def partial_update(self, request, *args, **kwargs):
        item = self.get_object()

        # FORM VALIDATION — validate_quantity and validate_price run here
        serializer = self.get_serializer(item, data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        item.order.compute_total()   # UPDATE total_price after item change
        return Response(serializer.data)

    # ── CRUD: DELETE ────────────────────────────────────────────
    def destroy(self, request, *args, **kwargs):
        item  = self.get_object()
        order = item.order

        # FORM VALIDATION — business rule: cannot remove items once shipped
        if order.status in ['shipped', 'delivered']:
            return Response(
                {"error": "Cannot remove items from a shipped or delivered order."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        item.delete()
        order.compute_total()   # UPDATE total_price after item removed
        return Response(status=status.HTTP_204_NO_CONTENT)


# ─────────────────────────────────────────────────────────────
# TABLE 3 — OrderNote ViewSet
# Endpoints (nested under order via urls.py):
#   POST   /api/orders/{order_pk}/notes/        → CREATE
#   GET    /api/orders/{order_pk}/notes/        → READ (list)
#   GET    /api/orders/{order_pk}/notes/{id}/   → READ (detail)
#   PATCH  /api/orders/{order_pk}/notes/{id}/   → UPDATE
#   DELETE /api/orders/{order_pk}/notes/{id}/   → DELETE
# ─────────────────────────────────────────────────────────────
class OrderNoteViewSet(viewsets.ModelViewSet):

    serializer_class   = OrderNoteSerializer
    permission_classes = [IsAuthenticated]

    def _get_order(self):
        """Helper — fetch parent Order and verify access."""
        try:
            order = Order.objects.get(pk=self.kwargs['order_pk'])
        except Order.DoesNotExist:
            raise NotFound("Order not found.")
        if order.user != self.request.user and not self.request.user.is_staff:
            raise PermissionDenied("You do not have access to this order.")
        return order

    # ── CRUD: READ ──────────────────────────────────────────────
    def get_queryset(self):
        return OrderNote.objects.filter(order=self._get_order())

    # ── CRUD: CREATE ────────────────────────────────────────────
    def perform_create(self, serializer):
        order = self._get_order()

        # FORM VALIDATION — non-staff cannot create staff-type notes
        note_type = self.request.data.get('note_type', 'customer')
        if note_type == 'staff' and not self.request.user.is_staff:
            raise PermissionDenied("Only staff members can create staff notes.")

        # FORM VALIDATION runs via serializer.is_valid() before perform_create is called
        serializer.save(order=order, author=self.request.user)

    # ── CRUD: UPDATE ────────────────────────────────────────────
    def partial_update(self, request, *args, **kwargs):
        note = self.get_object()

        # Permission: only the note author or staff can edit
        if note.author != request.user and not request.user.is_staff:
            raise PermissionDenied("You can only edit your own notes.")

        # FORM VALIDATION — validate_content and validate_note_type run here
        serializer = self.get_serializer(note, data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)

    # ── CRUD: DELETE ────────────────────────────────────────────
    def destroy(self, request, *args, **kwargs):
        note = self.get_object()

        # Permission: only the note author or staff can delete
        if note.author != request.user and not request.user.is_staff:
            raise PermissionDenied("You can only delete your own notes.")

        note.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
        order = serializer.save(user=self.request.user)

        # Create order items if provided
        items_data = request.data.get('items', [])
        for item in items_data:
            OrderItem.objects.create(
                order=order,
                product_id=item.get('product_id'),
                quantity=item.get('quantity', 1),
                price=item.get('price', 0)
            )

        return Response(OrderSerializer(order).data, status=status.HTTP_201_CREATED)

    @action(detail=True, methods=['post'], url_path='hide')
    def hide(self, request, pk=None):
        """Hide an order from the user's history (soft delete)"""
        order = self.get_object()

        # Only the owner can hide their own order
        if order.user != request.user:
            return Response({'detail': 'Not allowed.'}, status=status.HTTP_403_FORBIDDEN)

        order.is_hidden_by_user = True
        order.save()
        return Response({'detail': 'Order hidden.'}, status=status.HTTP_200_OK)